### ISSUE TITLE
on using multipart-params interceptor throwing excption

### ISSUE THREAD

**Issue by piyushmandovra** [pedestal/pedestal#297]
following is the stack trace of the issue

java.lang.IllegalArgumentException: No matching ctor found for class java.lang.Long
    at clojure.lang.Reflector.invokeConstructor(Reflector.java:183) [clojure-1.6.0.jar:]
    at ring.util.request$content_length.invoke(request.clj:27)
    at ring.middleware.multipart_params$request_context$reify__9942.getContentLength(multipart_params.clj:30)
    at org.apache.commons.fileupload.FileUploadBase$FileItemIteratorImpl.<init>(FileUploadBase.java:955) [commons-fileupload-1.3.jar:1.3]
    at org.apache.commons.fileupload.FileUploadBase.getItemIterator(FileUploadBase.java:310) [commons-fileupload-1.3.jar:1.3]
    at ring.middleware.multipart_params$file_item_seq.invoke(multipart_params.clj:46)
    at ring.middleware.multipart_params$parse_multipart_params.invoke(multipart_params.clj:62)
    at ring.middleware.multipart_params$multipart_params_request.doInvoke(multipart_params.clj:91)
    at clojure.lang.RestFn.invoke(RestFn.java:410) [clojure-1.6.0.jar:]
    at clojure.lang.AFn.applyToHelper(AFn.java:154) [clojure-1.6.0.jar:]
    at clojure.lang.RestFn.applyTo(RestFn.java:132) [clojure-1.6.0.jar:]
    at clojure.core$apply.invoke(core.clj:626) [clojure-1.6.0.jar:]

**Comment by EduardoMRB** [comment]
Hi, I'm going through the same bug, I'm fetching pedestal.service from leiningen (version "0.3.1") and I'm getting the old version of ``set-header`` function.

```clojure
expenses.server=> (source io.pedestal.http.impl.servlet-interceptor/set-header)
(defn- set-header [^HttpServletResponse servlet-resp h vs]
  (cond
   (= h "Content-Type") (.setContentType servlet-resp vs)
   (= h "Content-Length") (.setContentLength servlet-resp (Integer/parseInt vs))
   (string? vs) (.setHeader servlet-resp h vs)
   (sequential? vs) (doseq [v vs] (.addHeader servlet-resp h v))
   :else
   (throw (ex-info "Invalid header value" {:value vs}))))
nil
```

I  already deleted the ``io/pedestal/pedestal.service`` in ``~/.m2/repositories`` folder and fetched the dependency again, but the problem persist. Do I have to point my ``io.pedestal.service`` to a differente version inside the ``project.clj`` file?
