### ISSUE TITLE
500 response in hello world

### ISSUE THREAD

**Issue by jmeekr** [pedestal/pedestal#694]
# Description
On sending a request to "/greet" from http://pedestal.io/guides/hello-world tutorial
I get a 500 error and the below stack trace.

```
java.lang.IncompatibleClassChangeError: Found interface org.eclipse.jetty.http.pathmap.PathSpec, but class was expected
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:455)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.lang.Thread.run(Thread.java:748)
```

I have tried to copy the code directly to see if I've missed something and I still get the error.

I'm not sure how to parse the stack trace for `org.eclipse.jetty.http.pathmap.PathSpec, but class was expected`

## Expected Behavior
The response "Hello, world!"

## Actual Behavior
See description

## Steps to reproduce
Either navigating to the http://127.0.0.1:8080/greet or sending a curl request

# Environment

## Operating System (including version).
Fedora 32

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)
Using clj

## Pedestal version
0.5.7 and 0.5.8

**Comment by claj** [comment]
Are you using a version of Jetty later than 9? Because Pedestal only support up to version 9 (make sure to use the most recent version in, I think it is 9.4.44.v20210927). The interface `org.eclipse.jetty.http.pathmap.PathSpec` seems to be added in Jetty 10.

**Comment by jmeekr** [comment]
Hey thanks,

The server actually logs 
`[main] INFO org.eclipse.jetty.server.Server - jetty-9.4.36.v20210114; built: 2021-01-14T16:44:28.689Z; git: 238ec6997c7806b055319a6d11f8ae7564adc0de; jvm 1.8.0_292-b10`

If I setup a new project and only include what's in the tutorial it seems to work.  I've been trying to integrate it into a polylith project and am wondering if something about the namespacing is causing issues there.

**Comment by jmeekr** [comment]
Updating to "0.5.9" makes it work. :)
