### ISSUE TITLE
SSE: How to disable logging(WARN) of stacktrace on client disconnect

### ISSUE THREAD

**Issue by rawoke083** [pedestal/pedestal#720]
# Description
I've created a small pedestal SSE service template with jetty

When a client disconnects it seems **the whole stack track gets logged on a WARN level ?? ** 

## Expected Behavior

Either a way to disable the stacktrace  or change the logging level  the pedestal-service ?

## Actual Behavior

```

INFO  io.pedestal.http  - {:msg "GET /", :line 80}
WARN  i.p.http.impl.servlet-interceptor  - {:msg "The pipe closed while async writing to the client; Client most likely disconnected.", :line 112, :src-chan #object[clojure.core.async.impl.channels.ManyToManyChannel 0x63d8b138 "clojure.core.async.impl.channels.ManyToManyChannel@63d8b138"]}
org.eclipse.jetty.io.EofException: null
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:279)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:381)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:837)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:555)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:927)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:999)
	at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:285)
	at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:269)
	at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:751)
	at org.eclipse.jetty.server.Response.flushBuffer(Response.java:1110)
	at io.pedestal.http.impl.servlet_interceptor$fn__12536$fn__12652$state_machine__5646__auto____12661$fn__12666.invoke(servlet_interceptor.clj:102)
	at io.pedestal.http.impl.servlet_interceptor$fn__12536$fn__12652$state_machine__5646__auto____12661.invoke(servlet_interceptor.clj:102)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:978)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:982)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:980)
	at clojure.core.async.impl.ioc_macros$take_BANG_$fn__5664.invoke(ioc_macros.clj:991)
	at clojure.core.async.impl.channels.ManyToManyChannel$fn__603$fn__604.invoke(channels.clj:99)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at clojure.core.async.impl.concurrent$counted_thread_factory$reify__506$fn__507.invoke(concurrent.clj:29)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:66)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:217)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:153)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:563)
	at java.base/java.nio.channels.SocketChannel.write(SocketChannel.java:642)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:273)
	... 27 common frames omitted
INFO  io.pedestal.http.sse  - {:msg "Response channel was closed when sending event. Shutting down SSE stream.", :line 155}


```

## Steps to reproduce
Run example, disconnect client

# Environment
dev + prod (uberjar) ?
Clojure  1.11.1 ?
pedestal.jetty "0.5.10"

## Operating System (including version).
Linux (Ubuntu 20.04)

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)
Leiningen 2.9.1

## Pedestal version
0.5.10

**Comment by hlship** [comment]
Alas, this would likely require a code change to recognize this particular exception and suppress the logging.  It feels like the right way to do this would be to have a new option that can be used to filter or transform exceptions prior to being logged.

**Comment by hlship** [comment]
I think this is a particular subset of #623. Please re-open this issue if you disagree.
