### ISSUE TITLE
Server Startup Error

### ISSUE THREAD

**Issue by brown131** [pedestal/pedestal#802]
We have occasionally been getting the error below in our pedestal server. We have not been able to find any indication of exactly what the service is doing when this error occurs. The exception is getting caught by our unhandled exception handler, which shuts down the service after this error.

2024-01-31 09:02:04.991+0000 [async-dispatch-4] ERROR  server - uncaught exception thrown in thread async-dispatch-4, 86
clojure.lang.ExceptionInfo: java.lang.IllegalStateException in Interceptor :io.pedestal.http.impl.servlet-interceptor/stylobate - s=IDLE rs=COMPLETED os=ABORTED is=IDLE awp=false se=false i=false al=0
	at io.pedestal.interceptor.chain$throwable__GT_ex_info.invokeStatic(chain.clj:35)
	at io.pedestal.interceptor.chain$throwable__GT_ex_info.invoke(chain.clj:32)
	at io.pedestal.interceptor.chain$try_f.invokeStatic(chain.clj:57)
	at io.pedestal.interceptor.chain$try_f.invoke(chain.clj:44)
	at io.pedestal.interceptor.chain$leave_all_with_binding.invokeStatic(chain.clj:254)
	at io.pedestal.interceptor.chain$leave_all_with_binding.invoke(chain.clj:237)
	at io.pedestal.interceptor.chain$leave_all$fn__16949.invoke(chain.clj:268)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at io.pedestal.interceptor.chain$leave_all.invokeStatic(chain.clj:266)
	at io.pedestal.interceptor.chain$leave_all.invoke(chain.clj:260)
	at io.pedestal.interceptor.chain$execute.invokeStatic(chain.clj:379)
	at io.pedestal.interceptor.chain$execute.invoke(chain.clj:352)
	at io.pedestal.interceptor.chain$go_async$fn__16846$state_machine__5652__auto____16851$fn__16853.invoke(chain.clj:122)
	at io.pedestal.interceptor.chain$go_async$fn__16846$state_machine__5652__auto____16851.invoke(chain.clj:120)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:972)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:971)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:976)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:974)
	at clojure.core.async.impl.ioc_macros$take_BANG_$fn__5670.invoke(ioc_macros.clj:985)
	at clojure.core.async.impl.channels.ManyToManyChannel$fn__507.invoke(channels.clj:140)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at clojure.core.async.impl.concurrent$counted_thread_factory$reify__394$fn__395.invoke(concurrent.clj:29)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: s=IDLE rs=COMPLETED os=ABORTED is=IDLE awp=false se=false i=false al=0
	at org.eclipse.jetty.server.HttpChannelState.unhandle(HttpChannelState.java:417)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:654)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:439)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1525)
	at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:1225)
	at org.eclipse.jetty.server.HttpChannelState.complete(HttpChannelState.java:733)
	at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:72)
	at io.pedestal.http.impl.servlet_interceptor$leave_stylobate.invokeStatic(servlet_interceptor.clj:210)
	at io.pedestal.http.impl.servlet_interceptor$leave_stylobate.invoke(servlet_interceptor.clj:207)
	at io.pedestal.interceptor.chain$try_f.invokeStatic(chain.clj:54)
	... 28 common frames omitted

Versions:
pedstal: 0.6.3
jetty: 9.4.53.v20231009
clojure: 1.11.1
java: 11.0.20.1

**Comment by hlship** [comment]
This is unusual; I have not seen this before. Is it continuing to occur?  Do you see anything else odd in your logs?

**Comment by brown131** [comment]
This error happens several times a day for us. The issue started when we upgraded from Pedestal 0.5.10 to 0.6.3. Because this error is not happening in our error it was being caught by our uncaught exception handler, which treats such error as fatal and would shutdown the app.  Because of this we have since rolled-back to the 0.5.10 version.

A workaround might be to ignore the IllegalStateException errors in the uncaught exception handler and not shutdown. But we're not sure what state the server is in after this error, so it might not be a good idea to just ignore them.

**Comment by hlship** [comment]
i'm afraid there's nothing actionable for me here; please attach a sample project, or capture more logging information (perhaps enable debug logging of the io.pedestal.interceptors.chain namespace) and we can see if this is a problem in Pedestal.

**Comment by brown131** [comment]
I have to agree with you. We are unable to recreate this issue, and furthermore we have not seen this exception since then.
